### ISSUE TITLE
Assignment 5

### ISSUE THREAD

**Issue by mjzahn** [mjzahn/Assignment-5#1]
I have completed Assignment 5 where I used data from the [{FSAdata}](https://github.com/droglenc/FSAdata) package.

I was interested in relating weight and length measurements for Siscowet Lake Trout across the four sampling locations in Lake Superior. I created an exploratory plot and identified one outlier. Assuming that this outlier point was a data entry mistake (probably an extra zero), I removed this observation and investigated body length vs. weight for each site.

**Comment by mjzahn** [comment]
Tagging @mdscheuerell so he knows I've completed this assignment

**Comment by mdscheuerell** [comment]
I like your x-y plots with the trend lines and the different colors set them apart. Nice job, Marie!

One piece of advice: the relationship between length and weight (mass) is generally linear in log-log space, so I would recommend transforming the variables before fitting the lines.
